version: '3'

services:
  starorocks:
    image: starrocks/allin1-ubuntu:latest
    container_name: starorocks
    ports:
      - "9030:9030" 
      - "8030:8030"
      - "8040:8040"
    volumes:
      - /starorocks:/etc/starorocks  # Mapeamento do arquivo de configuração

  metabase:
    image: metabase/metabase-enterprise:latest
    container_name: metabase
    ports:
      - "3000:3000"  # Porta do Metabase   
    volumes:
      - /metabase-data:/metabase-data  # Mapeamento do volume de dados do Metabase

  tinyadmin:
    image: tinyfilemanager/tinyfilemanager:master
    container_name: tinyadmin
    ports:
      - "8081:80"  # Porta do TinyAdmin
    volumes:
      - /storage:/var/www/html/data
      - /dlpipelinepge/pipeline/airflow/dags:/var/www/html/data/dags  

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # Porta do Minio
      - "9001:9001"
    environment:      
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=Strong#Pass#2022    
    volumes:
      - /storage:/data  # Mapeamento do volume de dados do Minio
    command: server --console-address ":9001" /data

  jupyter:
    image: jupyter/base-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"  # Porta do Jupyter Notebook
    volumes:
      - /jupyter-notebooks:/home/jovyan/work  # Mapeamento do diretório de notebooks do Jupyter
      - /storage:/home/jovyan/storage
      - /dlpipelinepge/pipeline/airflow/dags:/home/jovyan/dags
    entrypoint: start.sh jupyter lab --NotebookApp.token=''

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

networks:
  default:
    external:
      name: airflow_default
