version: '3'

services:
  starorocks:
    image: registry.starrocks.io/starocks/allin1-ubuntu:latest
    container_name: starorocks
    ports:
      - 9030:9030 
      -	8030:8030
      - 8040:8040 # Porta da Starocks   
    volumes:
      - /starorocks:/etc/starorocks  # Mapeamento do arquivo de configuração

  metabase:
    image: metabase/metabase-enterprise:latest
    container_name: metabase
    ports:
      - "3000:3000"  # Porta do Metabase   
    volumes:
      - /metabase-data:/metabase-data  # Mapeamento do volume de dados do Metabase

  tinyadmin:
    image: tinyfilemanager/tinyfilemanager:master
    container_name: tinyadmin
    ports:
      - "8081:8080"  # Porta do TinyAdmin
    volumes:
      - /storage:/var/www/html/data

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9001:9000"  # Porta do Minio
    environment:
      - MINIO_ACCESS_KEY=seu_access_key
      - MINIO_SECRET_KEY=sua_secret_key
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=Strong#Pass#2022
    command: server --console-address ":9001" /data
    volumes:
      - /storage:/data  # Mapeamento do volume de dados do Minio

  jupyter:
    image: jupyter/base-notebook:latest
    container_name: jupyter
    ports:
      - "10000:8888"  # Porta do Jupyter Notebook
    volumes:
      - /jupyter-notebooks:/home/jovyan/work  # Mapeamento do diretório de notebooks do Jupyter
      - /storage:/home/jovyan/storage

networks:
  default:
    external:
      name: pipeline_default
